### ISSUE TITLE
Retrieve flags asap

### ISSUE THREAD

**Issue by Frollamma** [parmigggiana/attack_scripts#9]
At the moment, when running an exploit we it iterate over all the "vulnerable points" of an host, then we return a list of flags. This can be improved by yielding the flag as soon as its found, this way:
- If an error is encountered we don't have to attack previous vulnerable points, because we already got the flags
- We can send flags as soon as we get them, we don't have to wait to get an entire cargo of flags, of course we can decide to wait and send them in bulk, but if we know a flag is "old" (it means that it's gonna expire soon), we can send it immediately. This is particularly useful when dealing with "old" flags, like in #8

**Comment by parmigggiana** [comment]
Yield doesn't work like that; besides, that would increase massively the number of requests we make to the flag submission api resulting in us getting rate limited. A better approach to tackle the same issues would be ensuring the flags are sent just before the next gametick. Since the response is pretty slow we should figure out if the gameserver validates the flags based on submission time (in that case we can easily send them 5-10 seconds before the tick) or base on the elaboration time (we would need to account for that; slightly harder, but doable. In that case we wouldn't see many benefits though, since in the demo every response took upwards of 90 seconds, with 120 sec round duration.

**Comment by Frollamma** [comment]
When I said the "We can send flags as soon as we get them", I meant the we actually can do that, but if we think that it's better to the flags later we can do that as well. The idea is that Milkaman get the flags sooner this, therefore Milkman can send the flag when it think it's the best time to do so, without having to wait the whole flag cargo. Btw, I think that gameserver validates the flags depending on the submission, because:
- it wouldn't make much sense otherwise
- when you submit the flags the servers gets a request from you containing the flags, now its job is to parse that request and return a response. So the server has to some operations to determine if the flags are valid or not, then it sends the response. Basically the only operation it has to do is the flag checking, so it can't mark flags as valid or invalid based on the "elaboration time" since the elaboration has not ended yet while it is checking/parsing the flags!

**Comment by Frollamma** [comment]
So I agree with you that sending the flags 5 seconds before the gametick or so is a good idea, but it's still think that sending the flags to Milkman asap could be important as well in some cases (maybe it's rare, but it's still possible). For example we have a script that takes 3 second to run and it is getting some "old flags" (at next gametick they're gonna expire), but the gametick is just 2 seconds away... You see the problem here, when we send the flags we'll get as response that the flags are expired, if instead we sent them immediately we could get some valid flags. Of course we won't send flags immediately in any case, but just in case we think that we are getting old flags, for example it would be useful in case described in #3 .

**Comment by Frollamma** [comment]
I understand that it might be complicated to implement and this may have low priority, still it might be useful in the future

**Comment by parmigggiana** [comment]
> ... so it can't mark flags as valid or invalid based on the "elaboration time" since the elaboration has not ended yet while it is checking/parsing the flags!

No, the simpler approach would be to just each flag against the current set of valid flags. In that case, suppose the server is checking 50 flags and it takes 1 s for each. Depending on when during the checking process the gametick changes it might find more or less flags to be expired. We can't be sure of how they wrote the checker function just because of what makes more sense to us.




> So I agree with you that sending the flags 5 seconds before the gametick or so is a good idea, but it's still think that sending the flags to Milkman asap could be important as well in some cases (maybe it's rare, but it's still possible). For example we have a script that takes 3 second to run and it is getting some "old flags" (at next gametick they're gonna expire), but the gametick is just 2 seconds away... You see the problem here, when we send the flags we'll get as response that the flags are expired, if instead we sent them immediately we could get some valid flags. Of course we won't send flags immediately in any case, but just in case we think that we are getting old flags, for example it would be useful in case described in #3 .

I get your point, but that still isn't how yield works. Yield doesn't put the results in a list and keep going, it just gets the first resul and waits until you request for another one. It's exceptional for efficiency, but if you consider that most of the time any exploit spends if spent waiting for I/O network operation doing it like this would have the opposite result from what you expect.
Another approach to do what you suggest would be to use a global list and append to it instead of returning. That isn't hard to implement but would make it more complicated on the side of the user writing an exploit (returning is much more intuitive than importing a [Singleton](https://refactoring.guru/design-patterns/singleton) class and appending to it with proper multiprocess-safe locking). Maybe I can offload this burden in the launchAttack function and just add the flags to the database. I need to look more in depth into yield, maybe I can make it so it works with both yield and return. If not, I'll stick with return for it's ease of use

**Comment by parmigggiana** [comment]
As per commit 4065b2f, users are now free to use yield if they deem it preferable. Note that it may still not always be the best approach since before getting the next flag(s) we have to send the last one(s) to the database. If the exploit is really fast it's probably better to just return them all together. 
As a side note, I only tested yielding and returning one flag at a time. I don't expect it to misbehave when yielding a list (or returning a list - it was the previous behaviour) but we should keep an eye on it when we get the chance.
